package output

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"text/template"

	"github.com/navikt/naisalyser/internal/analyzer"
)

// GenerateMarkdown generates markdown documentation from analysis (interface-based)
func GenerateMarkdown(data interface{}, outputDir string) error {
	// Ensure output directory exists
	if err := os.MkdirAll(outputDir, 0755); err != nil {
		return fmt.Errorf("failed to create output directory: %w", err)
	}

	// Convert to unified view model
	vm := toViewModel(data)

	// Generate overview.md
	if err := generateOverviewVM(vm, outputDir); err != nil {
		return err
	}

	// Generate dependencies.md if we have deps
	if len(vm.Dependencies) > 0 {
		if err := generateDependenciesVM(vm, outputDir); err != nil {
			return err
		}
	}

	// Generate nais-config.md if we have nais config
	if vm.NaisConfig != nil {
		if err := generateNaisConfigVM(vm, outputDir); err != nil {
			return err
		}
	}

	return nil
}

// ViewModel is a unified structure for template rendering
type ViewModel struct {
	Name         string
	FullName     string
	URL          string
	Language     string
	Description  string
	NaisConfig   *analyzer.NaisConfig
	Dependencies []analyzer.Dependency
	Readme       string
}

func toViewModel(data interface{}) *ViewModel {
	switch v := data.(type) {
	case *analyzer.Analysis:
		return &ViewModel{
			Name:         v.Repository.Name,
			FullName:     v.Repository.FullName,
			URL:          v.Repository.URL,
			Language:     v.Repository.Language,
			Description:  v.Repository.Description,
			NaisConfig:   v.NaisConfig,
			Dependencies: v.Dependencies,
			Readme:       v.Readme,
		}
	case *analyzer.LocalAnalysis:
		return &ViewModel{
			Name:         v.Repository.Name,
			FullName:     v.Repository.FullName,
			URL:          fmt.Sprintf("https://github.com/%s", v.Repository.FullName),
			Language:     v.Repository.Language,
			Description:  v.Repository.Description,
			NaisConfig:   v.NaisConfig,
			Dependencies: v.Dependencies,
			Readme:       v.Readme,
		}
	default:
		return &ViewModel{}
	}
}

func generateOverviewVM(vm *ViewModel, outputDir string) error {
	tmpl := `# {{ .Name }}

> Auto-generated documentation by NAISalyser

## Overview

| Property | Value |
|----------|-------|
| **Repository** | [{{ .FullName }}]({{ .URL }}) |
| **Language** | {{ .Language }} |

## Description

{{ if .Description }}{{ .Description }}{{ else }}*No description provided*{{ end }}

{{- if .NaisConfig }}

## NAIS Application

| Property | Value |
|----------|-------|
| **App Name** | {{ .NaisConfig.Metadata.Name }} |
| **Namespace** | {{ .NaisConfig.Metadata.Namespace }} |
{{- if .NaisConfig.Spec.Port }}
| **Port** | {{ .NaisConfig.Spec.Port }} |
{{- end }}
{{- if .NaisConfig.Spec.Ingresses }}
| **Ingresses** | {{ len .NaisConfig.Spec.Ingresses }} configured |
{{- end }}

{{- if .NaisConfig.Spec.Ingresses }}

### Ingresses

{{ range .NaisConfig.Spec.Ingresses }}- {{ . }}
{{ end }}
{{- end }}

{{- end }}

---

*Generated by [NAISalyser](https://github.com/navikt/naisalyser)*
`

	return executeTemplate(tmpl, vm, filepath.Join(outputDir, "overview.md"))
}

func generateDependenciesVM(vm *ViewModel, outputDir string) error {
	tmpl := `# Dependencies

> Dependencies for {{ .Name }}

## Summary

Total dependencies: {{ len .Dependencies }}

## Dependencies

| Name | Version | Type |
|------|---------|------|
{{- range .Dependencies }}
| {{ .Name }} | {{ .Version }} | {{ .Type }} |
{{- end }}

---

*Generated by [NAISalyser](https://github.com/navikt/naisalyser)*
`

	return executeTemplate(tmpl, vm, filepath.Join(outputDir, "dependencies.md"))
}

func generateNaisConfigVM(vm *ViewModel, outputDir string) error {
	tmpl := `# NAIS Configuration

> NAIS configuration for {{ .Name }}

## Application Details

| Property | Value |
|----------|-------|
| **Name** | {{ .NaisConfig.Metadata.Name }} |
| **Namespace** | {{ .NaisConfig.Metadata.Namespace }} |
| **Kind** | {{ .NaisConfig.Kind }} |
| **API Version** | {{ .NaisConfig.APIVersion }} |

{{- if .NaisConfig.Spec.Replicas }}

## Scaling

| Min | Max |
|-----|-----|
| {{ .NaisConfig.Spec.Replicas.Min }} | {{ .NaisConfig.Spec.Replicas.Max }} |
{{- end }}

{{- if .NaisConfig.Spec.Resources }}
{{- if .NaisConfig.Spec.Resources.Requests }}

## Resources

### Requests
| CPU | Memory |
|-----|--------|
| {{ .NaisConfig.Spec.Resources.Requests.CPU }} | {{ .NaisConfig.Spec.Resources.Requests.Memory }} |
{{- end }}
{{- if .NaisConfig.Spec.Resources.Limits }}

### Limits
| CPU | Memory |
|-----|--------|
| {{ .NaisConfig.Spec.Resources.Limits.CPU }} | {{ .NaisConfig.Spec.Resources.Limits.Memory }} |
{{- end }}
{{- end }}

{{- if .NaisConfig.Spec.AccessPolicy }}
{{- if .NaisConfig.Spec.AccessPolicy.Inbound }}
{{- if .NaisConfig.Spec.AccessPolicy.Inbound.Rules }}

## Inbound Access Policy

| Application | Namespace | Cluster |
|-------------|-----------|---------|
{{- range .NaisConfig.Spec.AccessPolicy.Inbound.Rules }}
| {{ .Application }} | {{ .Namespace }} | {{ .Cluster }} |
{{- end }}
{{- end }}
{{- end }}

{{- if .NaisConfig.Spec.AccessPolicy.Outbound }}
{{- if .NaisConfig.Spec.AccessPolicy.Outbound.Rules }}

## Outbound Access Policy

| Application | Namespace | Cluster |
|-------------|-----------|---------|
{{- range .NaisConfig.Spec.AccessPolicy.Outbound.Rules }}
| {{ .Application }} | {{ .Namespace }} | {{ .Cluster }} |
{{- end }}
{{- end }}
{{- end }}
{{- end }}

{{- if .NaisConfig.Spec.GCP }}
{{- if .NaisConfig.Spec.GCP.SQLInstances }}

## Database (Cloud SQL)

{{ range .NaisConfig.Spec.GCP.SQLInstances }}
- Type: {{ .Type }}
{{- range .Databases }}
  - Database: {{ .Name }}
{{- end }}
{{ end }}
{{- end }}
{{- end }}

---

*Generated by [NAISalyser](https://github.com/navikt/naisalyser)*
`

	return executeTemplate(tmpl, vm, filepath.Join(outputDir, "nais-config.md"))
}

func executeTemplate(tmplContent string, data interface{}, outputPath string) error {
	funcMap := template.FuncMap{
		"joinTopics": func(topics []string) string {
			return strings.Join(topics, ", ")
		},
	}

	tmpl, err := template.New("doc").Funcs(funcMap).Parse(tmplContent)
	if err != nil {
		return fmt.Errorf("failed to parse template: %w", err)
	}

	f, err := os.Create(outputPath)
	if err != nil {
		return fmt.Errorf("failed to create output file: %w", err)
	}
	defer f.Close()

	if err := tmpl.Execute(f, data); err != nil {
		return fmt.Errorf("failed to execute template: %w", err)
	}

	return nil
}
